# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
